import type { Db } from "@/types";

// Remove
export const SEED_DATA: Db = {
  users: [
    {
      id: "user-1",
      email: "user1@example.com",
      name: "User One",
      avatarInitials: "U1",
      avatarBg: "#CCFCE7",
      avatarFg: "#065F46",
      isSeeded: true,
    },
    {
      id: "user-2",
      email: "sarah@example.com",
      name: "Sarah Adeyemi",
      avatarInitials: "SA",
      avatarBg: "#EDE9FE",
      avatarFg: "#5B21B6",
      isSeeded: true,
    },
    {
      id: "user-3",
      email: "marcus@example.com",
      name: "Marcus King",
      avatarInitials: "MK",
      avatarBg: "#FEF3C7",
      avatarFg: "#92400E",
      isSeeded: true,
    },
    {
      id: "user-4",
      email: "james@example.com",
      name: "James Thornton",
      avatarInitials: "JT",
      avatarBg: "#FFE4E6",
      avatarFg: "#9F1239",
      isSeeded: true,
    },
    {
      id: "user-5",
      email: "rosa@example.com",
      name: "Rosa Lima",
      avatarInitials: "RL",
      avatarBg: "#FCE7F3",
      avatarFg: "#9D174D",
      isSeeded: true,
    },
  ],
  groups: [
    {
      id: "group-1",
      name: "Portugal Trip",
      description: "Lisbon & Porto, May 2025",
      emoji: "✈️",
      createdBy: "user-1",
      createdAt: "2025-04-01T10:00:00Z",
      memberIds: ["user-1", "user-2", "user-3", "user-4", "user-5"],
    },
    {
      id: "group-2",
      name: "Flat Expenses",
      description: "Monthly shared costs",
      emoji: "🏠",
      createdBy: "user-1",
      createdAt: "2025-03-01T10:00:00Z",
      memberIds: ["user-1", "user-2", "user-3"],
    },
    {
      id: "group-3",
      name: "Work Lunches",
      description: "Team lunch rotation",
      emoji: "🍜",
      createdBy: "user-2",
      createdAt: "2025-02-01T10:00:00Z",
      memberIds: ["user-1", "user-2", "user-4"],
    },
  ],
  expenses: [
    {
      id: "exp-1",
      groupId: "group-1",
      paidBy: "user-2",
      description: "Airbnb deposit",
      amountPence: 24000,
      splitType: "equal",
      category: "accommodation",
      createdAt: "2025-04-10T12:00:00Z",
      splits: [
        { userId: "user-1", amountPence: 4800, isSettled: false },
        { userId: "user-2", amountPence: 4800, isSettled: true },
        { userId: "user-3", amountPence: 4800, isSettled: false },
        { userId: "user-4", amountPence: 4800, isSettled: false },
        { userId: "user-5", amountPence: 4800, isSettled: true },
      ],
    },
    {
      id: "exp-2",
      groupId: "group-1",
      paidBy: "user-2",
      description: "Dinner at Zé da Mouraria",
      amountPence: 9600,
      splitType: "equal",
      category: "food",
      createdAt: "2025-04-20T19:30:00Z",
      splits: [
        { userId: "user-1", amountPence: 1920, isSettled: false },
        { userId: "user-2", amountPence: 1920, isSettled: true },
        { userId: "user-3", amountPence: 1920, isSettled: false },
        { userId: "user-4", amountPence: 1920, isSettled: false },
        { userId: "user-5", amountPence: 1920, isSettled: true },
      ],
    },
    {
      id: "exp-3",
      groupId: "group-1",
      paidBy: "user-3",
      description: "Fado night tickets",
      amountPence: 7500,
      splitType: "equal",
      category: "activities",
      createdAt: "2025-04-21T20:00:00Z",
      splits: [
        { userId: "user-1", amountPence: 1500, isSettled: false },
        { userId: "user-2", amountPence: 1500, isSettled: false },
        { userId: "user-3", amountPence: 1500, isSettled: true },
        { userId: "user-4", amountPence: 1500, isSettled: false },
        { userId: "user-5", amountPence: 1500, isSettled: false },
      ],
    },
    {
      id: "exp-4",
      groupId: "group-2",
      paidBy: "user-1",
      description: "Internet bill",
      amountPence: 4500,
      splitType: "equal",
      category: "utilities",
      createdAt: "2025-04-01T09:00:00Z",
      splits: [
        { userId: "user-1", amountPence: 1500, isSettled: true },
        { userId: "user-2", amountPence: 1500, isSettled: true },
        { userId: "user-3", amountPence: 1500, isSettled: false },
      ],
    },
    {
      id: "exp-5",
      groupId: "group-2",
      paidBy: "user-2",
      description: "Grocery shop",
      amountPence: 9300,
      splitType: "equal",
      category: "food",
      createdAt: "2025-04-15T14:00:00Z",
      splits: [
        { userId: "user-1", amountPence: 3100, isSettled: false },
        { userId: "user-2", amountPence: 3100, isSettled: true },
        { userId: "user-3", amountPence: 3100, isSettled: false },
      ],
    },
  ],
  settlements: [
    {
      id: "settle-1",
      groupId: "group-2",
      payerId: "user-3",
      payeeId: "user-1",
      amountPence: 1500,
      status: "completed",
      mockPaymentId: "mock_pi_abc123",
      createdAt: "2025-04-05T10:00:00Z",
      settledAt: "2025-04-05T10:00:05Z",
    },
  ],
};

export const LIMITS = {
  MAX_GROUPS_PER_USER: 10,
  MAX_MEMBERS_PER_GROUP: 10,
  MAX_EXPENSES_PER_GROUP: 50,
} as const;
